# Generated by Django 5.1.1 on 2024-09-09 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=255)),
                ('emailaddress', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('bio', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Apparel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownership', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
                ('material', models.CharField(max_length=100)),
                ('upper_lower', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('image', models.BinaryField()),
                ('user', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apparels', to='userapp.user')),
            ],
        ),
    ]
