# Generated by Django 5.1.1 on 2024-09-16 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('gender', models.CharField(default='not specified', max_length=20, null=True)),
                ('Age', models.IntegerField(default='5', null=True)),
                ('bio', models.CharField(default='hi', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Apparel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('material', models.CharField(max_length=50)),
                ('upper_lower', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('image', models.BinaryField()),
                ('ownership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.user')),
            ],
        ),
    ]
