# Generated by Django 5.1.1 on 2024-10-10 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apparel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('material', models.CharField(max_length=50)),
                ('occasion', models.CharField(choices=[('CASUAL', 'Casual'), ('TRADITIONAL', 'Traditional'), ('FORMAL', 'Formal')], default='casual', max_length=20)),
                ('upper_lower', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='apparels/')),
            ],
        ),
        migrations.CreateModel(
            name='Combination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occasion', models.CharField(choices=[('CASUAL', 'Casual'), ('TRADITIONAL', 'Traditional'), ('FORMAL', 'Formal')], default='Casual', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='combinations/')),
                ('date_posted', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('shoe_image', models.ImageField(blank=True, null=True, upload_to='shoes/')),
            ],
        ),
        migrations.CreateModel(
            name='UpperAccessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('accessory_image', models.ImageField(blank=True, null=True, upload_to='upper_accessories/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('gender', models.CharField(default='not specified', max_length=20, null=True)),
                ('Age', models.IntegerField(default=5, null=True)),
                ('bio', models.CharField(default='hi', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Designs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default='black', max_length=50)),
                ('design_image', models.ImageField(blank=True, null=True, upload_to='designs/')),
                ('base_apparel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.apparel')),
            ],
        ),
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('attire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.combination')),
                ('shoes', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.shoes')),
                ('upperAccessories', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.upperaccessories')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acceptance', models.IntegerField(default=0)),
                ('remarks', models.CharField(default='cool', max_length=255)),
                ('ownership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.IntegerField(default=0)),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('ownership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.user')),
            ],
        ),
        migrations.AddField(
            model_name='combination',
            name='ownership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.user'),
        ),
        migrations.AddField(
            model_name='apparel',
            name='ownership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.user'),
        ),
    ]
