# Generated by Django 5.1.1 on 2024-10-09 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='age',
            new_name='Age',
        ),
    ]
