# Generated by Django 5.1.1 on 2024-09-13 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_remove_user_age_remove_user_bio_remove_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Age',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(default='hi.', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(default='not specified', null=True),
        ),
    ]
