# Generated by Django 5.1.1 on 2024-09-13 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_user_age_user_bio_user_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='emailaddress',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='apparel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Age',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
        migrations.AlterField(
            model_name='apparel',
            name='material',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='apparel',
            name='ownership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
