# Generated by Django 5.1.1 on 2024-09-13 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_rename_emailaddress_user_email_remove_apparel_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Age',
            field=models.IntegerField(default='5', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(default='hi', null=True),
        ),
    ]
