# Generated by Django 5.1.1 on 2024-10-05 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_attire_shoes_upperaccessories_designs_post_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='combination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.BinaryField()),
                ('ownership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.user')),
            ],
        ),
        migrations.AlterField(
            model_name='accessories',
            name='attire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.combination'),
        ),
        migrations.DeleteModel(
            name='Attire',
        ),
    ]
