# Generated by Django 5.1.1 on 2024-10-05 18:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0009_combination_alter_accessories_attire_delete_attire'),
    ]

    operations = [
        migrations.RenameField(
            model_name='designs',
            old_name='baseApparel',
            new_name='base_apparel',
        ),
        migrations.AddField(
            model_name='apparel',
            name='occasion',
            field=models.CharField(choices=[('CASUAL', 'Casual'), ('TRADITIONAL', 'Traditional'), ('FORMAL', 'Formal')], default='casual', max_length=20),
        ),
        migrations.AddField(
            model_name='combination',
            name='apparels',
            field=models.ManyToManyField(to='userapp.apparel'),
        ),
        migrations.AddField(
            model_name='combination',
            name='date_posted',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='combination',
            name='occasion',
            field=models.CharField(choices=[('CASUAL', 'Casual'), ('TRADITIONAL', 'Traditional'), ('FORMAL', 'Formal')], default='casual', max_length=20),
        ),
        migrations.AlterField(
            model_name='designs',
            name='color',
            field=models.CharField(default='black', max_length=50),
        ),
    ]
