# Generated by Django 5.1.1 on 2024-10-05 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0010_rename_baseapparel_designs_base_apparel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combination',
            name='occasion',
            field=models.CharField(choices=[('CASUAL', 'Casual'), ('TRADITIONAL', 'Traditional'), ('FORMAL', 'Formal')], default='Casual', max_length=20),
        ),
    ]
