# Generated by Django 5.1.1 on 2024-10-05 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0011_alter_combination_occasion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combination',
            name='apparels',
        ),
    ]
