# Generated by Django 5.1.1 on 2024-10-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0012_remove_combination_apparels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Age',
        ),
        migrations.AddField(
            model_name='designs',
            name='design_image',
            field=models.ImageField(blank=True, null=True, upload_to='designs/'),
        ),
        migrations.AddField(
            model_name='shoes',
            name='shoe_image',
            field=models.ImageField(blank=True, null=True, upload_to='shoes/'),
        ),
        migrations.AddField(
            model_name='upperaccessories',
            name='accessory_image',
            field=models.ImageField(blank=True, null=True, upload_to='upper_accessories/'),
        ),
        migrations.AlterField(
            model_name='apparel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='apparels/'),
        ),
        migrations.AlterField(
            model_name='combination',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='combinations/'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='remarks',
            field=models.CharField(default='cool', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.CharField(default='hi', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=5, null=True),
        ),
    ]
